version: "3.9"
services:
  app:
    container_name: iot-ttu-backend
    build:
      context: .
      dockerfile: Dockerfile
    #platform: linux/amd64
    ports:
      - "5180:80"
    depends_on:
      - db
    environment:
      - DOCKERDBCONNECTION=Server=iot-ttu-db:5432;Database=iot-ttu;Username=postgres;Password=postgres;
  db:
    container_name: iot-ttu-db
    image: "postgres:15.2-bullseye"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    #volumes:
      #- /Users/richardreintal/dev/iot-db:/var/lib/postgresql/data
#volumes:
#  db-volume:
#    driver: local
#    driver_opts:
#      type: none
#      device: /Users/richardreintal/dev/iot-db/
#      o: bind