version: "3.9"
services:
  app:
    container_name: ${DOCKER_APP}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${PORT} # This maps that the app is only accessible from inside the server (localhost)
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - IMAGES_DIRECTORY=${IMAGES_DIRECTORY}
      - IMAGES_LOCATION=${IMAGES_LOCATION}
      - IOT_JWT_ISSUER=${IOT_JWT_ISSUER}
      - IOT_JWT_AUDIENCE=${IOT_JWT_AUDIENCE}
      - JWT_KEY=${JWT_KEY}
      - APP_EMAIL=${APP_EMAIL}
    volumes:
      - type: bind
        source: ${IMAGES_DIRECTORY} # Host machine
        target: ${IMAGES_DIRECTORY} # Container path
  db:
    container_name: ${DOCKER_DB}
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 127.0.0.1:${DB_PORT} # This maps that the database is only accessible from inside the server (localhost)
    volumes:
      - type: bind
        source: ${LOCAL_PGDATA} # Local directory for PostgreSQL data
        target: /var/lib/postgresql/data