version: "3.9"
services:
  app:
    container_name: ${DOCKER_APP}
    build:
      context: .
      dockerfile: Dockerfile
    #platform: linux/amd64
    ports:
      - ${PORT}
    depends_on:
      - db
    env_file:
      - "./.env"
    environment:
      #- DOCKERDBCONNECTION=Server=iot-ttu-db:5432;Database=iot-ttu;Username=postgres;Password=postgres;   
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
  db:
    container_name: ${DOCKER_DB}
    image: "postgres:15.2-bullseye"
    restart: always
    
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - ${DB_PORT}
      #volumes:
      #- /Users/richardreintal/dev/iot-db:/var/lib/postgresql/data
#volumes:
#  db-volume:
#    driver: local
#    driver_opts:
#      type: none
#      device: /Users/richardreintal/dev/iot-db/
#      o: bind